export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'workbench',
    path: '/dashboard/workbench',
    title: '工作台',
    requiresAuth: true,
    icon: 'icon-park-outline:alarm',
    pinTab: true,
    menuType: 'page',
    componentPath: '/dashboard/workbench/index.vue',
    id: 1,
    pid: null,
  },
  {
    name: 'data_service',
    path: '/data',
    title: '数据管理',
    requiresAuth: true,
    icon: 'icon-park-outline:data',
    pinTab: true,
    menuType: 'dir',
    componentPath: null,
    id: 10,
    pid: null,
  },
  {
    name: 'data_project',
    path: '/data/project',
    title: '项目管理',
    requiresAuth: true,
    icon: 'icon-park-outline:projector-two',
    pinTab: true,
    menuType: 'page',
    componentPath: '/data/vehicle/projects.vue',
    id: 11,
    pid: 10,
  },
  {
    name: 'data_vehicle',
    path: '/data/vehicles',
    title: '车辆管理',
    requiresAuth: true,
    icon: 'icon-park-outline:engineering-vehicle',
    pinTab: true,
    menuType: 'page',
    componentPath: '/data/vehicle/vehicles.vue',
    id: 12,
    pid: 10,
  },
  {
    name: 'data_scripts',
    path: '/data/scripts',
    title: '脚本管理',
    requiresAuth: true,
    icon: 'icon-park-outline:play-two',
    pinTab: true,
    menuType: 'page',
    componentPath: '/data/scripts/ScriptList.vue',
    id: 13,
    pid: 10,
  },
  {
    name: 'data_scripts_exe',
    path: '/data/scripts/execution',
    title: '脚本执行记录',
    requiresAuth: true,
    hide: false,
    icon: 'icon-park-outline:list-one',
    pinTab: false,
    menuType: 'page',
    componentPath: '/data/scripts/ExecutionList.vue',
    id: 14,
    pid: 10,
  },
  {
    name: 'data_scripts_exe_detail',
    path: '/data/scripts/execution_detail',
    title: '脚本执行记录',
    requiresAuth: true,
    hide: true,
    icon: 'icon-park-outline:doc-detail',
    pinTab: false,
    menuType: 'page',
    componentPath: '/data/scripts/ExecutionDetail.vue',
    id: 14,
    pid: 10,
  },
]
