export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'workbench',
    path: '/dashboard/workbench',
    title: '工作台',
    requiresAuth: true,
    icon: 'icon-park-outline:alarm',
    pinTab: true,
    menuType: 'page',
    componentPath: '/dashboard/workbench/index.vue',
    id: 1,
    pid: null,
  },
  {
    name: 'demo',
    path: '/demo',
    title: '功能示例',
    requiresAuth: true,
    icon: 'icon-park-outline:application-one',
    menuType: 'dir',
    componentPath: null,
    id: 2,
    pid: null,
  },
  {
    name: 'test',
    path: '/test',
    title: '测试页面',
    requiresAuth: true,
    icon: 'icon-park-outline:menu-fold',
    componentPath: '/dashboard/test/index.vue',
    id: 3,
    pid: 2,
  },
  {
    name: 'errorHandlingTest',
    path: '/test/error-handling',
    title: '错误处理测试',
    requiresAuth: true,
    icon: 'icon-park-outline:bug',
    componentPath: '/test/error-handling.vue',
    id: 7,
    pid: 2,
  },
  {
    name: 'vehicle',
    path: '/vehicle',
    title: '项目管理',
    requiresAuth: true,
    icon: 'carbon:ibm-software-watsonx-data-analyze-and-process',
    menuType: 'dir',
    componentPath: null,
    id: 4,
    pid: null,
  },
  {
    name: ' project',
    path: '/project',
    title: '项目域管理',
    requiresAuth: true,
    icon: 'ant-design:product-outlined',
    componentPath: '/vehicle/spaceList.vue',
    id: 5,
    pid: 4,
  },
  {
    name: ' vehicles',
    path: '/project/vehicles',
    title: '车型管理',
    requiresAuth: true,
    icon: 'icon-park-outline:engineering-vehicle',
    componentPath: '/vehicle/vehicleList.vue',
    id: 6,
    pid: 4,
  },
]
