export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'workbench',
    path: '/dashboard/workbench',
    title: '工作台',
    requiresAuth: true,
    icon: 'icon-park-outline:alarm',
    pinTab: true,
    menuType: 'page',
    componentPath: '/dashboard/workbench/index.vue',
    id: 2,
    pid: null,
  },
  {
    name: 'demo',
    path: '/demo',
    title: '功能示例',
    requiresAuth: true,
    icon: 'icon-park-outline:application-one',
    menuType: 'dir',
    componentPath: null,
    id: 13,
    pid: null,
  },
  {
    name: 'test',
    path: '/test',
    title: '测试页面',
    requiresAuth: true,
    icon: 'icon-park-outline:menu-fold',
    componentPath: '/dashboard/test/index.vue',
    id: 45,
    pid: 13,
  },
  {
    name: 'test_main',
    path: '/test_main',
    title: '测试主页',
    requiresAuth: true,
    icon: 'icon-park-outline:menu-fold',
    componentPath: '/dashboard/main/index.vue',
    id: 45,
    pid: 13,
  },
]
